name: Merge PROD into PROD

on:
  push:
    branches:
      - DEV

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PROD Branch
      uses: actions/checkout@v3
      with:
        ref: PROD
        submodules: 'recursive'
        submodule-depth: 50

    - name: Merge PROD into DEV
      run: |
        git merge PROD
        git push origin PROD
    - name: Clean up
      run: |
        git branch -d PROD
